export const SECTION_20_REQUIREMENT_IDS = [
  '20.2.1',
  '20.2.2',
  '20.2.3',
  '20.2.4',
  '20.2.5',
  '20.2.6',
  '20.2.7',
  '20.2.8',
  '20.2.9',
  '20.2.10',
  '20.2.11',
  '20.2.12',
  '20.2.13',
  '20.2.14',
  '20.4.1.1',
  '20.4.1.2',
  '20.4.1.3',
  '20.4.1.4',
  '20.4.1.5',
  '20.5.partial',
  '20.5.final',
  '20.5.consume',
  '20.6.updated',
  '20.6.unchanged',
  '20.6.feedback-target',
  '20.6.child-route',
  '20.8.1',
  '20.8.2',
  '20.8.3',
  '20.8.4',
  '20.8.5',
  '20.8.6',
  '20.10.1',
  '20.10.2',
  '20.10.3',
  '20.10.4',
  '20.10.5',
  '20.10.6',
  '20.11.1',
  '20.11.2',
  '20.11.3',
  '20.11.4',
  '20.11.5',
  '20.12.start',
  '20.12.wait',
  '20.12.resolve',
  '20.12.consume',
  '20.12.failure',
  '20.12.reload',
  'A01',
  'A02',
  'A03',
  'A04',
  'A05',
  'A06',
  'A07',
  'A08',
  'A09',
  'A10',
  'A11',
  'A12',
  'A13',
  'A14',
] as const;

export type Section20RequirementId = (typeof SECTION_20_REQUIREMENT_IDS)[number];

export type Section20TraceabilityEntry = {
  requirementId: Section20RequirementId;
  targetTest: string;
  proof: 'behavior' | 'constraint';
  status: 'planned' | 'implemented';
};

const entry = (
  requirementId: Section20RequirementId,
  targetTest: string,
  proof: Section20TraceabilityEntry['proof'] = 'behavior',
  status: Section20TraceabilityEntry['status'] = 'planned',
): Section20TraceabilityEntry => ({ requirementId, targetTest, proof, status });

export const SECTION_20_TRACEABILITY: readonly Section20TraceabilityEntry[] = [
  entry('20.2.1', 'duplicate backend session ownership rejected', 'behavior', 'implemented'),
  entry('20.2.2', 'run timeout while no adapter process exists'),
  entry('20.2.3', 'three-producer fan-in concurrent final fills', 'behavior', 'implemented'),
  entry('20.2.4', 'three-producer fan-in concurrent final fills', 'behavior', 'implemented'),
  entry('20.2.5', 'session binding owner epoch and projection remain consistent', 'behavior', 'implemented'),
  entry('20.2.6', 'one-node top-level updated success and replay', 'behavior', 'implemented'),
  entry('20.2.7', 'targeted PREV updated plus unchanged ALL join'),
  entry('20.2.8', 'targeted PREV updated plus unchanged ALL join', 'behavior', 'implemented'),
  entry('20.2.9', 'caller and engine artifact provenance variants reject foreign ownership'),
  entry('20.2.10', 'nested PREV A-to-B-to-C returns to outer requester', 'behavior', 'implemented'),
  entry('20.2.11', 'late round-N response cannot satisfy round-N-plus-one'),
  entry('20.2.12', 'exact feedback and turn budget boundaries'),
  entry('20.2.13', 'definition rejects task routing fan-out'),
  entry('20.2.14', 'current schema rejects duplicate workflow task ownership', 'constraint', 'implemented'),
  entry('20.4.1.1', 'multi-entry exact caller contracts schedule concurrently'),
  entry('20.4.1.2', 'multi-entry exact caller contracts schedule concurrently'),
  entry('20.4.1.3', 'caller and engine artifact provenance variants reject foreign ownership'),
  entry('20.4.1.4', 'multi-entry exact caller contracts schedule concurrently'),
  entry('20.4.1.5', 'start commits before scheduling every entry activation'),
  entry('20.5.partial', 'three-producer fan-in concurrent final fills', 'behavior', 'implemented'),
  entry('20.5.final', 'three-producer fan-in concurrent final fills', 'behavior', 'implemented'),
  entry('20.5.consume', 'reload at every gate/round/continuation state is idempotent', 'behavior', 'implemented'),
  entry('20.6.updated', 'one-node top-level updated success and replay', 'behavior', 'implemented'),
  entry('20.6.unchanged', 'targeted PREV updated plus unchanged ALL join'),
  entry('20.6.feedback-target', 'late round-N response cannot satisfy round-N-plus-one'),
  entry('20.6.child-route', 'root caller invokes multi-entry child and consumes return', 'behavior', 'implemented'),
  entry('20.8.1', 'targeted PREV updated plus unchanged ALL join'),
  entry('20.8.2', 'reload at every gate/round/continuation state is idempotent'),
  entry('20.8.3', 'nested PREV A-to-B-to-C returns to outer requester', 'behavior', 'implemented'),
  entry('20.8.4', 'late round-N response cannot satisfy round-N-plus-one'),
  entry('20.8.5', 'targeted PREV updated plus unchanged ALL join', 'behavior', 'implemented'),
  entry('20.8.6', 'feedback final responder value is present', 'behavior', 'implemented'),
  entry('20.10.1', 'stale NEXT racing cancellation is harmless'),
  entry('20.10.2', 'three-producer fan-in concurrent final fills', 'behavior', 'implemented'),
  entry('20.10.3', 'targeted PREV updated plus unchanged ALL join'),
  entry('20.10.4', 'concurrent disposition staging and failed-turn discard', 'behavior', 'implemented'),
  entry('20.10.5', 'terminal-run queued turn rejected by scheduler and SQL claim', 'behavior', 'implemented'),
  entry('20.10.6', 'explicit activation recovery replay conflict and cancellation race'),
  entry('20.11.1', 'three-level child failure recursively closes root', 'behavior', 'implemented'),
  entry('20.11.2', 'three-level child cancellation recursively closes root', 'behavior', 'implemented'),
  entry('20.11.3', 'terminal-run queued turn rejected by scheduler and SQL claim', 'behavior', 'implemented'),
  entry('20.11.4', 'typed failed and cancelled continuation results survive reload', 'behavior', 'implemented'),
  entry('20.11.5', 'three-level child failure recursively closes root', 'behavior', 'implemented'),
  entry('20.12.start', 'root caller invokes multi-entry child and consumes return', 'behavior', 'implemented'),
  entry('20.12.wait', 'root caller invokes multi-entry child and consumes return', 'behavior', 'implemented'),
  entry('20.12.resolve', 'typed failed and cancelled continuation results survive reload', 'behavior', 'implemented'),
  entry('20.12.consume', 'root caller invokes multi-entry child and consumes return', 'behavior', 'implemented'),
  entry('20.12.failure', 'three-level child failure recursively closes root', 'behavior', 'implemented'),
  entry('20.12.reload', 'reload at every gate/round/continuation state is idempotent', 'behavior', 'implemented'),
  entry('A01', 'three-producer fan-in concurrent final fills', 'behavior', 'implemented'),
  entry('A02', 'stale NEXT racing cancellation is harmless'),
  entry('A03', 'same opId concurrent define/start conflict'),
  entry('A04', 'same child key across callers remains isolated'),
  entry('A05', 'current schema rejects duplicate workflow task ownership', 'constraint', 'implemented'),
  entry('A06', 'current schema rejects conflicting gate input pins', 'constraint', 'implemented'),
  entry('A07', 'relational feedback identity rejects contradictory JSON'),
  entry('A08', 'duplicate backend session ownership rejected', 'constraint', 'implemented'),
  entry('A09', 'explicit activation recovery replay conflict and cancellation race'),
  entry('A10', 'retention preserves open workflow evidence', 'behavior', 'implemented'),
  entry('A11', 'terminal run rejects stale activation but permits later ordinary turn'),
  entry('A12', 'workflow start applies ordinary host policy', 'behavior', 'implemented'),
  entry('A13', 'workflow entries inherit caller subtree and root limits'),
  entry('A14', 'required target lifecycle seal recursively closes workflow', 'behavior', 'implemented'),
] as const;
