export const SECTION_20_REQUIREMENT_IDS = [
  '20.2.1',
  '20.2.2',
  '20.2.3',
  '20.2.4',
  '20.2.5',
  '20.2.6',
  '20.2.7',
  '20.2.8',
  '20.2.9',
  '20.2.10',
  '20.2.11',
  '20.2.12',
  '20.2.13',
  '20.2.14',
  '20.4.1.1',
  '20.4.1.2',
  '20.4.1.3',
  '20.4.1.4',
  '20.4.1.5',
  '20.5.partial',
  '20.5.final',
  '20.5.consume',
  '20.6.updated',
  '20.6.unchanged',
  '20.6.feedback-target',
  '20.6.child-route',
  '20.8.1',
  '20.8.2',
  '20.8.3',
  '20.8.4',
  '20.8.5',
  '20.8.6',
  '20.10.1',
  '20.10.2',
  '20.10.3',
  '20.10.4',
  '20.10.5',
  '20.10.6',
  '20.11.1',
  '20.11.2',
  '20.11.3',
  '20.11.4',
  '20.11.5',
  '20.12.start',
  '20.12.wait',
  '20.12.resolve',
  '20.12.consume',
  '20.12.failure',
  '20.12.reload',
  'A01',
  'A02',
  'A03',
  'A04',
  'A05',
  'A06',
  'A07',
  'A08',
  'A09',
  'A10',
  'A11',
  'A12',
  'A13',
  'A14',
] as const;

export type Section20RequirementId = (typeof SECTION_20_REQUIREMENT_IDS)[number];

export type Section20TraceabilityEntry = {
  requirementId: Section20RequirementId;
  targetFile: string;
  targetTest: string;
  proof: 'behavior' | 'constraint';
  status: 'planned' | 'implemented';
};

const entry = (
  requirementId: Section20RequirementId,
  targetFile: string,
  targetTest: string,
  proof: Section20TraceabilityEntry['proof'] = 'behavior',
): Section20TraceabilityEntry => ({
  requirementId,
  targetFile,
  targetTest,
  proof,
  status: 'implemented',
});

export const SECTION_20_TRACEABILITY: readonly Section20TraceabilityEntry[] = [
  entry('20.2.1', 'm018-s09-session-ownership.test.ts', 'duplicate backend session ownership rejected'),
  entry('20.2.2', 'm018-s05-fail-fast-cancellation-budgets.test.ts', 'engine load reaps an expired waiting workflow without starting an adapter'),
  entry('20.2.3', 'm018-s02-fan-in-next.test.ts', 'three-producer fan-in concurrent final fills'),
  entry('20.2.4', 'm018-s02-fan-in-next.test.ts', 'three-producer fan-in concurrent final fills'),
  entry('20.2.5', 'm018-s09-session-ownership.test.ts', 'session binding owner epoch and projection remain consistent'),
  entry('20.2.6', 'm018-s01-one-node-workflow.test.ts', 'one-node top-level updated success and replay'),
  entry('20.2.7', 'm018-s04-prev-feedback-all-join.test.ts', 'nested PREV preserves outer response authority across requester resume and reload'),
  entry('20.2.8', 'm018-s04-prev-feedback-all-join.test.ts', 'PREV ALL-join: open round, partial no resume, final ordered resume, redelivery no-op, identities only'),
  entry('20.2.9', 'm018-s01-one-node-workflow.test.ts', 'one-node top-level updated success and replay'),
  entry('20.2.10', 'm018-s04-prev-feedback-all-join.test.ts', 'nested PREV preserves outer response authority across requester resume and reload'),
  entry('20.2.11', 'm018-s04-prev-feedback-all-join.test.ts', 'late round-N response cannot satisfy round-N-plus-one'),
  entry('20.2.12', 'm018-s05-fail-fast-cancellation-budgets.test.ts', 'per-task turn limits admit exact NEXT and feedback boundaries, then fail the next PREV'),
  entry('20.2.13', 'm018-s02-fan-in-next.test.ts', 'public define accepts graph_v1 fan-in topology and rejects malformed graphs'),
  entry('20.2.14', 'sqlite/schema.ts', 'uq_workflow_nodes_task_owner', 'constraint'),
  entry('20.4.1.1', 'm018-s07-canonical-workflow.test.ts', 'assembled flow: fan-in → planner → verifier PREV once → correction → terminal NEXT; status + scheduler throughout'),
  entry('20.4.1.2', 'm018-s07-canonical-workflow.test.ts', 'assembled flow: fan-in → planner → verifier PREV once → correction → terminal NEXT; status + scheduler throughout'),
  entry('20.4.1.3', 'm018-s07-canonical-workflow.test.ts', 'assembled flow: fan-in → planner → verifier PREV once → correction → terminal NEXT; status + scheduler throughout'),
  entry('20.4.1.4', 'm018-s07-canonical-workflow.test.ts', 'assembled flow: fan-in → planner → verifier PREV once → correction → terminal NEXT; status + scheduler throughout'),
  entry('20.4.1.5', 'm018-s07-canonical-workflow.test.ts', 'assembled flow: fan-in → planner → verifier PREV once → correction → terminal NEXT; status + scheduler throughout'),
  entry('20.5.partial', 'm018-s02-fan-in-next.test.ts', 'three-producer fan-in concurrent final fills'),
  entry('20.5.final', 'm018-s02-fan-in-next.test.ts', 'three-producer fan-in concurrent final fills'),
  entry('20.5.consume', 'm018-s03-reload-redelivery.test.ts', 'post-prune NEXT redelivery is a no-op under durable contribution fence'),
  entry('20.6.updated', 'm018-s01-one-node-workflow.test.ts', 'one-node top-level updated success and replay'),
  entry('20.6.unchanged', 'm018-s04-prev-feedback-all-join.test.ts', 'nested PREV preserves outer response authority across requester resume and reload'),
  entry('20.6.feedback-target', 'm018-s04-prev-feedback-all-join.test.ts', 'late round-N response cannot satisfy round-N-plus-one'),
  entry('20.6.child-route', 'm018-s06-child-workflow-continuation.test.ts', 'an ordinary root coordinator invokes a child and resumes through its return gate'),
  entry('20.8.1', 'm018-s04-prev-feedback-all-join.test.ts', 'targeted PREV from_p1 only opens one target and single response resumes requester'),
  entry('20.8.2', 'm018-s04-prev-feedback-all-join.test.ts', 'reload between partial and final response preserves open round and yields one resume'),
  entry('20.8.3', 'm018-s04-prev-feedback-all-join.test.ts', 'nested PREV preserves outer response authority across requester resume and reload'),
  entry('20.8.4', 'm018-s04-prev-feedback-all-join.test.ts', 'late round-N response cannot satisfy round-N-plus-one'),
  entry('20.8.5', 'm018-s04-prev-feedback-all-join.test.ts', 'PREV ALL-join: open round, partial no resume, final ordered resume, redelivery no-op, identities only'),
  entry('20.8.6', 'm018-s04-prev-feedback-all-join.test.ts', 'concurrent final feedback responses build one exact aggregate'),
  entry('20.10.1', 'm018-s10-terminal-activation-guard.test.ts', 'terminal closure before the settlement write lock commits no stale workflow effect'),
  entry('20.10.2', 'm018-s02-fan-in-next.test.ts', 'three-producer fan-in concurrent final fills'),
  entry('20.10.3', 'm018-s04-prev-feedback-all-join.test.ts', 'PREV ALL-join: open round, partial no resume, final ordered resume, redelivery no-op, identities only'),
  entry('20.10.4', 'm018-s08-disposition-claims.test.ts', 'cross-family disposition races have exactly one winner'),
  entry('20.10.5', 'm018-s10-terminal-activation-guard.test.ts', 'terminal run rejects stale activation but permits later ordinary turn'),
  entry('20.10.6', 'm018-s05-fail-fast-cancellation-budgets.test.ts', 'explicit activation recovery replay conflict and cancellation race'),
  entry('20.11.1', 'm018-s06-child-workflow-continuation.test.ts', 'three-level child failure recursively closes every run and boundary once'),
  entry('20.11.2', 'm018-s06-child-workflow-continuation.test.ts', 'three-level child cancellation preserves lifecycle authority and typed cancellation'),
  entry('20.11.3', 'm018-s10-terminal-activation-guard.test.ts', 'terminal run rejects stale activation but permits later ordinary turn'),
  entry('20.11.4', 'm018-s06-child-workflow-continuation.test.ts', 'reload after child return does not duplicate resume; child fail propagates continuation once'),
  entry('20.11.5', 'm018-s06-child-workflow-continuation.test.ts', 'three-level child failure recursively closes every run and boundary once'),
  entry('20.12.start', 'm018-s06-child-workflow-continuation.test.ts', 'an ordinary root coordinator invokes a child and resumes through its return gate'),
  entry('20.12.wait', 'm018-s06-child-workflow-continuation.test.ts', 'an ordinary root coordinator invokes a child and resumes through its return gate'),
  entry('20.12.resolve', 'm018-s06-child-workflow-continuation.test.ts', 'child terminal NEXT resolves continuation once and queues exactly one caller resume; redelivery is a no-op'),
  entry('20.12.consume', 'm018-s06-child-workflow-continuation.test.ts', 'an ordinary root coordinator invokes a child and resumes through its return gate'),
  entry('20.12.failure', 'm018-s06-child-workflow-continuation.test.ts', 'three-level child failure recursively closes every run and boundary once'),
  entry('20.12.reload', 'm018-s06-child-workflow-continuation.test.ts', 'reload after child return does not duplicate resume; child fail propagates continuation once'),
  entry('A01', 'm018-s02-fan-in-next.test.ts', 'three-producer fan-in concurrent final fills'),
  entry('A02', 'm018-s10-terminal-activation-guard.test.ts', 'terminal closure before the settlement write lock commits no stale workflow effect'),
  entry('A03', 'm018-s01-one-node-workflow.test.ts', 'same-operation concurrent define and start converge to one immutable definition and run'),
  entry('A04', 'm018-s06-child-workflow-continuation.test.ts', 'same child key is isolated across callers and conflicts on changed same-caller bindings'),
  entry('A05', 'sqlite/schema.ts', 'uq_workflow_nodes_task_owner', 'constraint'),
  entry('A06', 'sqlite/schema.ts', 'PRIMARY KEY (workspace_id, run_id, gate_id, input_ref)', 'constraint'),
  entry('A07', 'm018-s04-prev-feedback-all-join.test.ts', 'nested PREV preserves outer response authority across requester resume and reload'),
  entry('A08', 'm018-s09-session-ownership.test.ts', 'duplicate backend session ownership rejected'),
  entry('A09', 'm018-s05-fail-fast-cancellation-budgets.test.ts', 'explicit activation recovery replay conflict and cancellation race'),
  entry('A10', 'm018-s06-child-workflow-continuation.test.ts', 'an ordinary root coordinator invokes a child and resumes through its return gate'),
  entry('A11', 'm018-s08-disposition-claims.test.ts', 'rejects a workflow disposition on a non-workflow turn without a claim'),
  entry('A12', 'm018-s08-disposition-claims.test.ts', 'workflow start applies ordinary host policy and persists effective clamps'),
  entry('A13', 'm018-s08-disposition-claims.test.ts', 'child workflow start applies host policy before staging and freezes effective clamps'),
  entry('A14', 'm018-s05-fail-fast-cancellation-budgets.test.ts', 'premature succeeded, failed, and skipped lifecycle seals close the workflow as unavailable'),
] as const;
