import { describe, expect, it } from 'vitest';
import {
  FILE_DROP_MAX_CANDIDATES,
  FILE_DROP_MAX_CANDIDATE_LENGTH,
  extractFileDropCandidates,
  isOsFileManagerDrag,
  isVsCodeExplorerDrag,
  type FileDropData,
} from './file-drop';

function transfer(input: Partial<FileDropData> = {}): FileDropData {
  return {
    files: input.files ?? [],
    types: input.types ?? [],
    getData: input.getData ?? (() => ''),
  };
}

describe('extractFileDropCandidates', () => {
  it.each([
    {
      name: 'normalizes URI-list comments, blank lines, and CRLF without decoding',
      value: '# generated by browser\r\nfile:///workspace/a%20b.ts\r\n\r\nfile:///workspace/c.ts\r\n',
      expected: ['file:///workspace/a%20b.ts', 'file:///workspace/c.ts'],
    },
    {
      name: 'hands percent encoding to the host unchanged',
      value: 'file:///workspace/%E2%9C%93.ts',
      expected: ['file:///workspace/%E2%9C%93.ts'],
    },
  ])('$name', ({ value, expected }) => {
    const data = transfer({
      types: ['text/uri-list'],
      getData: (type) => (type === 'text/uri-list' ? value : ''),
    });
    expect(extractFileDropCandidates(data, true)).toEqual({ ok: true, candidates: expected });
  });

  it('uses an explicit File.path but never falls back to File.name', () => {
    const data = transfer({ files: [{ name: 'ignored.ts' }, { name: 'safe.ts', path: '/workspace/safe.ts' }] });
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['/workspace/safe.ts'],
    });
  });

  it('accepts explicit plain-text transfer data as one opaque host candidate', () => {
    const data = transfer({
      types: ['text/plain', 'text/html'],
      getData: (type) => (type === 'text/plain' ? 'src/a.ts' : '<b>secret</b>'),
    });
    expect(extractFileDropCandidates(data, true)).toEqual({ ok: true, candidates: ['src/a.ts'] });
  });

  it('rejects disabled composer', () => {
    expect(extractFileDropCandidates(transfer(), false)).toEqual({
      ok: false,
      code: 'disabled',
      message: 'File drop is unavailable.',
    });
  });

  it('rejects unsupported MIME-only drops', () => {
    const result = extractFileDropCandidates(
      transfer({ types: ['text/html'], getData: () => '<b>x</b>' }),
      true,
    );
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.code).toBe('noData');
  });

  it('rejects empty URI lists', () => {
    const result = extractFileDropCandidates(
      transfer({ types: ['text/uri-list'], getData: () => '# comment\n' }),
      true,
    );
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.code).toBe('noData');
  });

  it('accepts Finder-style File.path when MIME payloads are empty', () => {
    const data = transfer({
      files: [{ name: 'a.ts', path: '/Users/me/projects/muster/src/a.ts' }],
      types: ['Files'],
      getData: () => '',
    });
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['/Users/me/projects/muster/src/a.ts'],
    });
  });

  it('falls back to bare file names when absolute paths are stripped', () => {
    const result = extractFileDropCandidates(
      transfer({
        files: [{ name: 'a.ts' }],
        types: ['Files'],
        getData: () => '',
      }),
      true,
    );
    expect(result).toEqual({ ok: true, candidates: ['a.ts'] });
  });

  it('rejects excessive candidates instead of truncating silently', () => {
    const value = Array.from({ length: FILE_DROP_MAX_CANDIDATES + 1 }, (_, i) => `file:///workspace/${i}.ts`).join('\n');
    expect(extractFileDropCandidates(transfer({ types: ['text/uri-list'], getData: () => value }), true)).toEqual({
      ok: false,
      code: 'tooManyCandidates',
      message: `Drop at most ${FILE_DROP_MAX_CANDIDATES} file candidates.`,
    });
  });

  it('rejects overlong and NUL-containing path-like candidates', () => {
    // Overlong absolute-style path still recognized then rejected as invalid.
    const tooLong = `/${'a'.repeat(FILE_DROP_MAX_CANDIDATE_LENGTH)}`;
    expect(
      extractFileDropCandidates(transfer({ types: ['text/plain'], getData: () => tooLong }), true),
    ).toEqual({
      ok: false,
      code: 'invalidCandidate',
      message: 'Dropped file data is malformed or too long.',
    });
    // NUL cannot be a valid path candidate — treated as no usable data.
    const nulResult = extractFileDropCandidates(
      transfer({ types: ['text/plain'], getData: () => 'file:///workspace/a\0.ts' }),
      true,
    );
    expect(nulResult.ok).toBe(false);
  });

  it('prefers a single MIME source over merging File.path with uri-list', () => {
    const data = transfer({
      files: [{ path: '/workspace/a.ts' }],
      types: ['text/uri-list', 'Files'],
      getData: (type) => (type === 'text/uri-list' ? 'file:///workspace/a.ts' : ''),
    });
    // uri-list wins over File.path — one candidate, not two encodings of the same file.
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['file:///workspace/a.ts'],
    });
  });

  it('prefers resourceurls over other Explorer MIME payloads', () => {
    const data = transfer({
      files: [{ path: '/workspace/src/extension.ts' }],
      types: ['resourceurls', 'text/uri-list', 'Files'],
      getData: (type) => {
        if (type.toLowerCase() === 'resourceurls') {
          return JSON.stringify(['file:///workspace/src/extension.ts']);
        }
        if (type === 'text/uri-list') return 'file:///workspace/src/extension.ts';
        return '';
      },
    });
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['file:///workspace/src/extension.ts'],
    });
  });

  it('extracts VS Code Explorer resourceurls JSON payloads', () => {
    const data = transfer({
      types: ['resourceurls'],
      getData: (type) =>
        type.toLowerCase() === 'resourceurls'
          ? JSON.stringify(['file:///workspace/src/extension.ts', 'file:///workspace/docs/a.md'])
          : '',
    });
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['file:///workspace/src/extension.ts', 'file:///workspace/docs/a.md'],
    });
  });

  it('extracts VS Code codeeditors descriptors', () => {
    const data = transfer({
      types: ['codeeditors'],
      getData: (type) =>
        type.toLowerCase() === 'codeeditors'
          ? JSON.stringify([
              { resource: { external: 'file:///workspace/src/a.ts', fsPath: '/workspace/src/a.ts' } },
            ])
          : '',
    });
    expect(extractFileDropCandidates(data, true)).toEqual({
      ok: true,
      candidates: ['file:///workspace/src/a.ts'],
    });
  });

  it('detects VS Code Explorer vs OS file-manager drag MIME types', () => {
    expect(isVsCodeExplorerDrag(['resourceurls', 'Files'])).toBe(true);
    expect(isVsCodeExplorerDrag(['text/plain'])).toBe(false);
    expect(isOsFileManagerDrag(['Files'])).toBe(true);
    expect(isOsFileManagerDrag(['resourceurls', 'Files'])).toBe(false);
  });
});
